# Generated by Django 5.2.4 on 2025-07-31 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
                ('descripcion', models.CharField(help_text='Ej: 8:00 am, 2:00 pm', max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Aplazado', 'Aplazado'), ('Retirado', 'Retirado')], default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='valor_cuota_pactada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='valor_paquete_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.nivel'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.horario'),
        ),
    ]
