# Generated by Django 5.2.4 on 2025-07-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0003_horario_estudiante_estado_estudiante_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='estado',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Aplazado', 'Aplazado'), ('Retirado', 'Retirado'), ('Graduado', 'Graduado')], default='Activo', max_length=10),
        ),
    ]
