# Generated by Django 5.2.4 on 2025-07-31 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0004_remove_horario_estado_remove_nivel_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='valor_cuota_pactada',
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_cuotas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_cuota_pactada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Parcial', 'Parcial')], default='Pendiente', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.contrato')),
            ],
        ),
    ]
