# Generated by Django 5.2.4 on 2025-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0005_remove_estudiante_valor_cuota_pactada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
