# Generated by Django 5.2.4 on 2025-08-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0006_pago_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento', 'numero']},
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_clientes.cuota'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('contrato', 'numero')},
        ),
    ]
