# Generated by Django 5.2.4 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0007_alter_cuota_options_pago_cuota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=10),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], max_length=10),
        ),
    ]
