# Generated by Django 5.2.4 on 2025-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0008_estudiante_documento_estudiante_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
