# Generated by Django 5.2.4 on 2025-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0009_alter_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_factura',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Banco', 'Banco'), ('Nequi', 'Nequi'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
