# Generated by Django 5.2.4 on 2025-09-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0011_backfill_pago_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
