# Generated by Django 5.2.4 on 2025-09-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0012_pago_referencia_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] No usar en nuevo flujo; usar PagoAplicacion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_clientes.cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='PagoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='gestion_clientes.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.pago')),
            ],
            options={
                'indexes': [models.Index(fields=['pago'], name='gestion_cli_pago_id_7b9395_idx'), models.Index(fields=['cuota'], name='gestion_cli_cuota_i_501474_idx')],
                'unique_together': {('pago', 'cuota')},
            },
        ),
    ]
