# Generated by Django 5.2.4 on 2025-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0013_alter_pago_cuota_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_vencimiento'], name='gestion_cli_fecha_v_7c1ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estado'], name='gestion_cli_estado_35d55a_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='gestion_cli_fecha_p_5e67c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_factura'], name='gestion_cli_numero__99b5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['referencia'], name='gestion_cli_referen_3cacf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagoaplicacion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pagoap_monto_gt_0'),
        ),
    ]
