# Generated by Django 5.2.4 on 2025-09-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0014_cuota_gestion_cli_fecha_v_7c1ae1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='valor_paquete_total',
        ),
    ]
