# Generated by Django 5.2.4 on 2025-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0015_remove_estudiante_valor_paquete_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
