# Generated by Django 5.2.4 on 2025-10-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0016_alter_acudiente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_ingreso', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'gestion_financiera_ingreso',
                'managed': False,
            },
        ),
    ]
