# Generated by Django 5.2.4 on 2025-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0018_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='sede',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sedes',
            field=models.ManyToManyField(blank=True, to='gestion_clientes.sede'),
        ),
    ]
