# Generated by Django 5.2.4 on 2025-12-14 05:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0019_remove_perfil_sede_perfil_sedes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion_clientes.acudiente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion_clientes.estudiante'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_cuota_pactada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='gestion_clientes_contrato',
        ),
    ]
