# Generated by Django 5.2.4 on 2025-12-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0020_alter_contrato_options_alter_contrato_acudiente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'managed': False, 'ordering': ['fecha_vencimiento', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagoaplicacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'managed': False},
        ),
    ]
